name: Trunk
on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Start Docker
      run: sudo make start-docker

    - name: Maven Build & Test
      run: sudo make wars
