name: Trunk
on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Maven Build & Test
      run: sudo make wars
